import * as vscode from 'vscode';
import WebSocket from 'ws';
import * as crypto from 'crypto';
import { startBackend, stopBackend, BackendHandle } from './backend';

let handle: BackendHandle | undefined;
let sessionToken: string;

export function activate(context: vscode.ExtensionContext) {
    sessionToken = crypto.randomBytes(32).toString('hex');

    // MUST come before startBackend - it takes this as an argument.
    const outputChannel = vscode.window.createOutputChannel('AI Agent Backend');
    outputChannel.appendLine('Starting Python backend...');

    const ready: Promise<BackendHandle> = Promise.resolve(
        vscode.window.withProgress(
            { location: vscode.ProgressLocation.Window, title: 'Starting AI Agent backend...' },
            () => startBackend(context, sessionToken, outputChannel)
        )
    ).then(h => { handle = h; return h; });

    ready.catch((err: any) => {
        outputChannel.appendLine(`\n[AI Agent] ${err.message}`);
        vscode.window.showErrorMessage(`AI Agent backend failed to start: ${err.message}`);
    });

    const setKeyCommand = vscode.commands.registerCommand('ai-agent.setApiKey', async () => {
        const apiKey = await vscode.window.showInputBox({
            prompt: 'Enter your Gemini API Key',
            password: true
        });
        if (apiKey) {
            await context.secrets.store('gemini_api_key', apiKey);
            vscode.window.showInformationMessage('API Key saved!');
        }
    });

    const disposable = vscode.commands.registerCommand('ai-agent.openChat', async () => {
        const apiKey = await context.secrets.get('gemini_api_key');
        if (!apiKey) {
            vscode.window.showWarningMessage('Please set your API key first using "AI Agent: Set API Key"');
            return;
        }

        const folders = vscode.workspace.workspaceFolders;
        if (!folders || folders.length === 0) {
            vscode.window.showErrorMessage('Please open a project folder before using AI Agent.');
            return;
        }
        const workingDir = folders[0].uri.fsPath;

        // Ask once per workspace whether the agent may execute code. Stored in
        // workspaceState, so trusting your own repo does not trust a stranger's.
        let allowExecution = context.workspaceState.get<boolean>('allowExecution');

        if (allowExecution === undefined && vscode.workspace.isTrusted) {
            const choice = await vscode.window.showWarningMessage(
                'AI Agent can run Python files in this workspace. Code may be generated by ' +
                'the AI or reconstructed from a YouTube video, and it runs with your full ' +
                'user permissions — there is no sandbox. Enable execution?',
                { modal: true },
                'Enable execution',
                'Read-only mode'
            );
            allowExecution = choice === 'Enable execution';
            await context.workspaceState.update('allowExecution', allowExecution);
        }

        const executionEnabled = Boolean(allowExecution) && vscode.workspace.isTrusted;

        // Wait for the backend to report its port before opening the panel.
        let h: BackendHandle;
        try {
            h = await ready;
        } catch (err: any) {
            vscode.window.showErrorMessage(`Backend unavailable: ${err.message}`);
            return;
        }

        const panel = vscode.window.createWebviewPanel(
            'aiAgentChat', 'AI AGENT', vscode.ViewColumn.One,
            { enableScripts: true, retainContextWhenHidden: true, localResourceRoots:[vscode.Uri.joinPath(context.extensionUri,'media')]}
        );
        const logoUri=panel.webview.asWebviewUri(
            vscode.Uri.joinPath(context.extensionUri,'media','logo.png')
        )
        panel.webview.html = getChatHtml(panel.webview,logoUri);

        let socket: WebSocket | null = null;
        let retryAttempts = 0;
        // was 10 - the port is known now, so this only covers the ms gap before accept()
        const MAX_RETRY_ATTEMPTS = 3;
        let retryTimeout: NodeJS.Timeout | undefined;

        function connect() {
            panel.webview.postMessage({ type: 'connectionState', state: 'connecting' });
            socket = new WebSocket(`ws://127.0.0.1:${h.port}/chat`, {
                headers: { 'x-agent-token': h.token }
            });

            socket.on('open', () => {
                retryAttempts = 0; // was never reset before
                socket!.send(JSON.stringify({
                    type: 'auth',
                    api_key: apiKey!,
                    allow_execution: executionEnabled
                }));
                socket!.send(workingDir);
                panel.webview.postMessage({ type: 'status', text: 'Connected to backend.' });
                panel.webview.postMessage({ type: 'connectionState', state: 'connected' });
            });

            socket.on('message', (data) => {
                const text = data.toString();
                if (text.startsWith('ASK:')) {
                    try {
                        panel.webview.postMessage({ type: 'ask', payload: JSON.parse(text.slice(4)) });
                    } catch {
                        // malformed ASK payload - ignore
                    }
                }
                else if (text.startsWith('QUOTA:')){
                    panel.webview.postMessage({type:'quota',text: text.slice(6)});
                } 
                else if (text.startsWith('UPDATE:')) {
                    panel.webview.postMessage({ type: 'update', text: text.replace('UPDATE:', '') });
                } 
                else if (text.startsWith('DONE:')) {
                    panel.webview.postMessage({ type: 'done', text: text.replace('DONE:', '') });
                }
                 else {
                    panel.webview.postMessage({ type: 'update', text: text });
                }
        });

            socket.on('error', (err: any) => {
                if (err.code === 'ECONNREFUSED' && retryAttempts < MAX_RETRY_ATTEMPTS) {
                    retryAttempts++;
                    panel.webview.postMessage({ type: 'connectionState', state: 'connecting' });
                    retryTimeout = setTimeout(connect, 500);
                } else {
                    panel.webview.postMessage({ type: 'connectionState', state: 'disconnected' });
                    panel.webview.postMessage({ type: 'status', text: 'Connection error: ' + err.message });
                }
            });

            socket.on('close', () => {
                panel.webview.postMessage({ type: 'connectionState', state: 'disconnected' });
            });
        }

        connect();

        panel.webview.onDidReceiveMessage((message) => {
            if (message.type === 'prompt') {
                if (!socket || socket.readyState === WebSocket.CLOSED || socket.readyState === WebSocket.CLOSING) {
                    connect();
                }
                const payload = JSON.stringify({ type: 'prompt', text: message.text });

                if (socket!.readyState === WebSocket.OPEN) {
                    socket!.send(payload);
                } else {
                    socket!.once('open', () => socket!.send(payload));
                }
            } else if (message.type === 'approval') {
                socket?.send(JSON.stringify({ type: 'approval', id: message.id, approved: message.approved }));
            } else if (message.type === 'cancel') {
                socket?.send(JSON.stringify({ type: 'cancel' }));
            }
        });

        panel.onDidDispose(() => {
            if (retryTimeout) { clearTimeout(retryTimeout); }
            socket?.close();
        });
    });

    context.subscriptions.push(setKeyCommand, disposable, outputChannel);
}

export function deactivate() {
    stopBackend(handle?.process);
    handle = undefined;
}

function getChatHtml(webview: vscode.Webview, logoUri: vscode.Uri): string {
    const nonce = getNonce();
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${webview.cspSource}; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'; connect-src ws://127.0.0.1:*;">
    <style>
        /* Height chain so the chat window scrolls inside its own box instead
           of the whole page growing. Purely functional - the panel looks the
           same, long conversations just behave. */
        html, body {
            height: 100%;
        }

        body {
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            font-family: var(--vscode-font-family);
            background: var(--vscode-editor-background);
            color: var(--vscode-editor-foreground);
        }

        .message-wrapper {
            display: flex;
            width: 100%;
            margin-bottom: 12px;
        }

        .message-wrapper.you {
            justify-content: flex-end;
        }

        .message-wrapper.agent, .message-wrapper.system {
            justify-content: flex-start;
        }

        .chat-bubble {
            max-width: 85%;
            padding: 10px 14px;
            border-radius: 12px;
            line-height: 1.5;
            word-wrap: break-word;
        }

        .chat-bubble.you {
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            border-bottom-right-radius: 4px;
        }

        .chat-bubble.agent {
            background: #34C759;
            border: 1px solid var(--vscode-widget-border);
            color: var(--vscode-editor-background);
            border-bottom-left-radius: 4px;
        }

        .chat-bubble.system {
            background: transparent;
            font-style: italic;
            font-size: 12px;
            padding: 4px 0;
            border: 1px solid var(--vscode-widget-border);
            color: var(--vscode-editor-foreground);
            border-bottom-left-radius: 4px;
        }

        .code-block {
            position: relative;
            background: var(--vscode-textCodeBlock-background);
            border: 1px solid var(--vscode-widget-border);
            border-radius: 8px;
            padding: 12px;
            margin: 8px 0;
            overflow-x: auto;
            font-family: var(--vscode-editor-font-family);
            font-size: 13px;
            color: var(--vscode-editor-foreground)
        }

        .code-lang {
            font-size: 11px;
            text-transform: uppercase;
            color: var(--vscode-editor-foreground);
            margin-bottom: 6px;
            opacity:0.55;
        }

        /* ADDED: copy button on code blocks */
        .copy-button {
            position: absolute;
            top: 6px;
            right: 6px;
            display: flex;
            align-items: center;
            justify-content: center;
            width: 24px;
            height: 24px;
            padding: 0;
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-editorWidget-background);
            color: var(--vscode-descriptionForeground);
            cursor: pointer;
            opacity: 0;
            transition: opacity 0.12s;
        }

        .code-block:hover .copy-button,
        .copy-button:focus {
            opacity: 1;
        }

        .copy-button:hover {
            color: var(--vscode-editor-foreground);
            background: var(--vscode-list-hoverBackground);
        }

        /* ADDED: collapsible tool-call trace */
        .tool-trace {
            align-self: flex-start;
            max-width: 85%;
            margin-bottom: 12px;
            font-size: 12px;
            color: var(--vscode-descriptionForeground);
        }

        .tool-trace summary {
            display: inline-flex;
            align-items: center;
            gap: 7px;
            padding: 3px 11px 3px 9px;
            border: 1px solid var(--vscode-widget-border);
            border-radius: 20px;
            cursor: pointer;
            list-style: none;
            user-select: none;
        }

        .tool-trace summary::-webkit-details-marker { display: none; }
        .tool-trace summary:hover { background: var(--vscode-list-hoverBackground); }

        .trace-chevron {
            transition: transform 0.15s ease;
            flex-shrink: 0;
        }

        .tool-trace[open] .trace-chevron { transform: rotate(90deg); }

        .tool-trace-steps {
            margin: 7px 0 0 13px;
            padding-left: 13px;
            border-left: 1px solid var(--vscode-widget-border);
            display: flex;
            flex-direction: column;
            gap: 4px;
        }

        .tool-trace-step {
            font-family: var(--vscode-editor-font-family);
            font-size: 11.5px;
            word-wrap: break-word;
        }

        .approval-card {
            max-width: 95%;
            border: 1px solid var(--vscode-inputValidation-warningBorder);
            border-radius: 12px;
            padding: 14px;
            background: var(--vscode-editorWidget-background);
        }

        .approval-header {
            font-weight: 600;
            margin-bottom: 8px;
            color: var(--vscode-editor-foreground);
        }

        .approval-buttons {
            display: flex;
            gap: 8px;
            margin-top: 10px;
        }

        .approval-buttons button {
            padding: 6px 14px;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            font-family: var(--vscode-font-family);
        }

        .btn-approve {
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
        }

        .btn-reject {
            background: transparent;
            color: var(--vscode-editor-foreground);
            border: 1px solid var(--vscode-widget-border) !important;
        }

        .status-bar {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 12px;
            font-size: 13px;
            /* Use muted foreground for secondary text */
            color: var(--vscode-descriptionForeground);
        }

        .status-dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            background: #999;
        }

        /* Error states */
        .dot-connecting { background: #e0a800; }
        .dot-connected { background: #22c48c; }
        .dot-disconnected { background: #d9534f; }
        .dot-backend_down { background: #d9534f; }

        .agent-container {
            display: flex;
            flex-direction: column;
            width: 100%;
            flex: 1;
            min-height: 0;
            padding: 20px;
            box-sizing: border-box;
            background-color: transparent;
        }

        .agent-title {
            margin-top: 0;
            font-size: 22px;
            color: var(--vscode-editor-foreground);
        }
        
        .agent-title-row{
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: 16px;
        }
        .agent-logo{
        width: 32px;
        height: 32px;
        border-radius: 7px;
        flex-shrink: 0;
    }

        .chat-window {
            flex: 1;
            min-height: 0;
            padding: 16px;
            background-color: var(--vscode-editorWidget-background);
            border-radius: 12px;
            border: 1px solid var(--vscode-widget-border);
            overflow-y: auto;
        }

        .chat-text {
            margin: 0 0 12px;
            line-height: 1.5;
        }

        /* ADDED: rendered markdown inside message bubbles */
        .md-p {
            margin: 0 0 10px;
            line-height: 1.6;
            overflow-wrap: anywhere;
        }

        .md-p:last-child, .md-list:last-child, .md-h:last-child { margin-bottom: 0; }

        .md-h {
            font-weight: 650;
            line-height: 1.3;
            margin: 16px 0 8px;
            letter-spacing: -0.01em;
        }

        .md-h:first-child { margin-top: 0; }
        .md-h1 { font-size: 1.3em; }
        .md-h2 { font-size: 1.16em; }
        .md-h3 { font-size: 1.05em; }

        .md-list {
            margin: 0 0 10px;
            padding-left: 22px;
        }

        .md-list li {
            margin-bottom: 6px;
            line-height: 1.6;
            overflow-wrap: anywhere;
        }

        .md-list li:last-child { margin-bottom: 0; }
        .md-list li::marker { opacity: 0.65; }

        .md-strong { font-weight: 700; }
        .md-em { font-style: italic; }

        .inline-code {
            font-family: var(--vscode-editor-font-family);
            font-size: 0.92em;
            padding: 1px 5px;
            border-radius: 4px;
            background: rgba(255,255,255,0.5);
            white-space: nowrap;
        }

        .md-link {
            color: inherit;
            text-decoration: underline;
            text-underline-offset: 2px;
            font-weight: 600;
        }

        .md-hr {
            border: none;
            border-top: 1px solid currentColor;
            opacity: 0.28;
            margin: 14px 0;
        }

        /* ADDED: composer replaces the absolutely-positioned buttons */
        .input-area {
            position: relative;
            margin-top: 18px;
        }

        .composer {
            border: 1px solid var(--vscode-input-border, var(--vscode-widget-border));
            border-radius: 12px;
            background: var(--vscode-input-background);
            overflow: hidden;
        }

        /* Ring on the container - box-shadow follows the radius where an
           outline would square off the rounded corners. */
        .composer:focus-within {
            border-color: transparent;
            box-shadow: 0 0 0 1.5px var(--vscode-focusBorder);
        }

        .prompt-input {
            display: block;
            width: 100%;
            min-height: 44px;
            max-height: 180px;
            padding: 12px 13px 4px;
            border: none;
            background: transparent;
            color: var(--vscode-input-foreground);
            font-family: var(--vscode-font-family);
            font-size: 14px;
            line-height: 1.5;
            resize: none;
            overflow-y: auto;
            box-sizing: border-box;
        }

        .prompt-input:focus { outline: none; }

        .composer-footer {
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 5px 7px 7px 13px;
        }

        .composer-hint {
            font-size: 10.5px;
            color: var(--vscode-descriptionForeground);
            opacity: 0.8;
        }
        
        .composer-actions {
            display: flex;
            align-items: center;
            gap: 7px;
            margin-left: auto;
        }

        .typing-indicator {
            display: flex;
            gap: 6px;
            padding: 14px 18px;
            min-height: 24px;
        }

        .dot {
            width: 6px;
            height: 6px;
            background-color: var(--vscode-editor-background);
            border-radius: 50%;
            opacity: 0.4;
            animation: pulse 1.4s infinite ease-in-out both;
        }

        .dot:nth-child(1) { animation-delay: -0.32s; }
        .dot:nth-child(2) { animation-delay: -0.16s; }

        @keyframes pulse {
            0%, 80%, 100% { transform: scale(0.6); opacity: 0.3; }
            40% { transform: scale(1.1); opacity: 1; }
        }

        @media (prefers-reduced-motion: reduce) {
            .dot { animation: none; opacity: 0.55; }
            .trace-chevron { transition: none; }
        }

        #send-button {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            height: 28px;
            width: 28px;
            border-radius: 50%;
            border: none;
            /* Match native VS Code buttons */
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            cursor: pointer;
        }

        /* hovering the send button changes the cursor */
        #send-button:hover:not(:disabled) {
            background: var(--vscode-button-hoverBackground);
        }

        #quota-text {
            margin-left: auto;
            opacity: 0.75;
            font-size: 11px;
            }
        #send-button:disabled {
            opacity: 0.4;
            cursor: default;
        }

        #cancel-button {
            display: none;
            align-items: center;
            gap: 6px;
            height: 28px;
            padding: 0 11px;
            border-radius: 14px;
            border: 1px solid var(--vscode-errorForeground);
            background: transparent;
            color: var(--vscode-errorForeground);
            font-family: var(--vscode-font-family);
            font-size: 11.5px;
            cursor: pointer;
        }

        #cancel-button:hover {
            background: var(--vscode-inputValidation-errorBackground);
        }

        button:focus-visible, summary:focus-visible {
            outline: none;
            box-shadow: 0 0 0 2px var(--vscode-focusBorder);
        }
    </style>
</head>
<body>
    <div class="status-bar" id="status-bar">
        <span class="status-dot" id="status-dot"></span>
        <span id="status-text">Connecting...</span>
        <span id="quota-text"></span>
    </div>
    <div class="agent-container">
        <div class="agent-title-row">
            <img class="agent-logo" src="${logoUri}" alt="" />
            <h1 class="agent-title">AI AGENT</h1>
        </div>
        <div class="chat-window" id="chat-window">
            <p class="chat-text">Agent: System initialized. Ready to code.</p>
        </div>
        <div class="input-area">
            <div class="composer">
                <textarea id="prompt-box" rows="1" placeholder="Type your prompt here..." class="prompt-input"></textarea>
                <div class="composer-footer">
                    <span class="composer-hint">Enter to send &middot; Shift+Enter for a new line</span>
                    <div class="composer-actions">
                        <button id="cancel-button" type="button" aria-label="Stop the current task"></button>
                        <button id="send-button" type="button" aria-label="Send message"></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script nonce="${nonce}">
        const vscode = acquireVsCodeApi();
        const textarea = document.getElementById('prompt-box');
        const sendButton = document.getElementById('send-button');
        const cancelButton = document.getElementById('cancel-button');
        const chatWindow = document.getElementById('chat-window');
        const statusDot = document.getElementById('status-dot');
        const statusText = document.getElementById('status-text');
        const quotaText = document.getElementById('quota-text');

        // Fixed, developer-authored icon markup. Never combined with user or
        // model text, so innerHTML is safe for these specifically.
        const SEND_ICON = '<svg width="15" height="15" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M8 13.5V3M3.5 7.5L8 3L12.5 7.5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
        const STOP_ICON = '<svg width="9" height="9" viewBox="0 0 10 10" fill="currentColor" aria-hidden="true"><rect width="10" height="10" rx="2.5"/></svg>';
        const COPY_ICON = '<svg width="13" height="13" viewBox="0 0 14 14" fill="none" aria-hidden="true"><rect x="5" y="5" width="8" height="8" rx="1.8" stroke="currentColor" stroke-width="1.25"/><path d="M9.2 5V2.8A1.8 1.8 0 0 0 7.4 1H2.8A1.8 1.8 0 0 0 1 2.8V7.4A1.8 1.8 0 0 0 2.8 9.2H5" stroke="currentColor" stroke-width="1.25"/></svg>';
        const CHECK_ICON = '<svg width="13" height="13" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="M2.8 7.4L5.6 10.2L11.2 4" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
        const CHEVRON_ICON = '<svg class="trace-chevron" width="9" height="9" viewBox="0 0 10 10" fill="none" aria-hidden="true"><path d="M3.5 1.5L7 5L3.5 8.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';

        // Built from char codes, not escape sequences. This script lives
        // inside a TS template literal where a stray backslash is consumed
        // before the browser ever sees it.
        const NL = String.fromCharCode(10);
        const TICK = String.fromCharCode(96);
        const FENCE = TICK + TICK + TICK;

        sendButton.innerHTML = SEND_ICON;
        cancelButton.innerHTML = STOP_ICON + '<span>Stop</span>';

        // --- Chat persistence (getState/setState) ---
        // Keeps the conversation across the webview being hidden and shown
        // again (tab switches). chatLog holds only plain addMessage entries;
        // pending approval cards and in-progress trace steps are
        // intentionally not persisted.
        let chatLog = [];

        function saveState() {
            vscode.setState({ chatLog });
        }

        const previousState = vscode.getState();
        if (previousState && previousState.chatLog && previousState.chatLog.length > 0) {
            chatWindow.innerHTML = '';
            chatLog = previousState.chatLog;
            chatLog.forEach(entry => renderMessage(entry.text, entry.sender));
        }

        function setConnectionState(state){
            statusDot.className='status-dot dot-' + state;
            const labels={
                connecting: 'Connecting...',
                connected: 'Connected',
                disconnected: 'Disconnected - waiting to reconnect',
                backend_down: 'Backend unavailable'

            };
            statusText.textContent=labels[state] || state;

            const isConnected = state ==='connected';
            textarea.disabled= !isConnected;
            sendButton.disabled=!isConnected;

        }

        // ADDED: copy-to-clipboard for code blocks
        function fallbackCopy(text) {
            const ta = document.createElement('textarea');
            ta.value = text;
            ta.style.position = 'fixed';
            ta.style.opacity = '0';
            document.body.appendChild(ta);
            ta.focus();
            ta.select();
            try { document.execCommand('copy'); } catch (e) { /* no-op */ }
            document.body.removeChild(ta);
        }

        function copyText(text) {
            if (navigator.clipboard && navigator.clipboard.writeText) {
                return navigator.clipboard.writeText(text)['catch'](function () { fallbackCopy(text); });
            }
            fallbackCopy(text);
            return Promise.resolve();
        }

        function makeCopyButton(codeText) {
            const btn = document.createElement('button');
            btn.className = 'copy-button';
            btn.type = 'button';
            btn.setAttribute('aria-label', 'Copy code');
            btn.innerHTML = COPY_ICON;
            btn.addEventListener('click', function () {
                copyText(codeText).then(function () {
                    btn.innerHTML = CHECK_ICON;
                    setTimeout(function () { btn.innerHTML = COPY_ICON; }, 1200);
                });
            });
            return btn;
        }

        // --- Markdown rendering -------------------------------------
        // Hand-written so there is no external dependency and no innerHTML
        // on model text. Every piece of text still lands via textContent,
        // so nothing from Gemini is ever parsed as HTML.

        function isBullet(s) {
            const c = s.charAt(0);
            return (c === '*' || c === '-' || c === '+') && s.charAt(1) === ' ';
        }

        function stripBullet(s) {
            return s.slice(1).trim();
        }

        function numberedLen(s) {
            let j = 0;
            while (j < s.length && s.charAt(j) >= '0' && s.charAt(j) <= '9') { j++; }
            if (j > 0 && s.charAt(j) === '.' && s.charAt(j + 1) === ' ') { return j + 1; }
            return 0;
        }

        // Inline: bold, italic, inline code, and [label](url) links
        function parseInline(container, text) {
            let i = 0;
            let buf = '';

            function flushBuf() {
                if (buf) {
                    container.appendChild(document.createTextNode(buf));
                    buf = '';
                }
            }

            while (i < text.length) {
                const ch = text.charAt(i);

                if (ch === TICK) {
                    const close = text.indexOf(TICK, i + 1);
                    if (close !== -1) {
                        flushBuf();
                        const codeEl = document.createElement('code');
                        codeEl.className = 'inline-code';
                        codeEl.textContent = text.slice(i + 1, close);
                        container.appendChild(codeEl);
                        i = close + 1;
                        continue;
                    }
                }

                if (ch === '*' && text.charAt(i + 1) === '*') {
                    const close = text.indexOf('**', i + 2);
                    if (close !== -1 && close > i + 2) {
                        flushBuf();
                        const strong = document.createElement('span');
                        strong.className = 'md-strong';
                        parseInline(strong, text.slice(i + 2, close));
                        container.appendChild(strong);
                        i = close + 2;
                        continue;
                    }
                }

                // Single * or _ for italic, but only when it clearly wraps a
                // word - avoids mangling things like "2 * 3" or snake_case.
                if ((ch === '*' || ch === '_') && text.charAt(i + 1) !== ' ') {
                    const close = text.indexOf(ch, i + 1);
                    if (close !== -1 && close > i + 1 && text.charAt(close - 1) !== ' ') {
                        flushBuf();
                        const em = document.createElement('span');
                        em.className = 'md-em';
                        parseInline(em, text.slice(i + 1, close));
                        container.appendChild(em);
                        i = close + 1;
                        continue;
                    }
                }

                if (ch === '[') {
                    const closeBracket = text.indexOf(']', i);
                    if (closeBracket !== -1 && text.charAt(closeBracket + 1) === '(') {
                        const closeParen = text.indexOf(')', closeBracket);
                        if (closeParen !== -1) {
                            flushBuf();
                            const label = text.slice(i + 1, closeBracket);
                            const url = text.slice(closeBracket + 2, closeParen);
                            // Only http(s) becomes a real link - never
                            // javascript: or data: from model output.
                            if (url.slice(0, 7) === 'http://' || url.slice(0, 8) === 'https://') {
                                const a = document.createElement('a');
                                a.className = 'md-link';
                                a.href = url;
                                a.textContent = label;
                                container.appendChild(a);
                            } else {
                                container.appendChild(document.createTextNode(label));
                            }
                            i = closeParen + 1;
                            continue;
                        }
                    }
                }

                buf += ch;
                i++;
            }
            flushBuf();
        }

        // Block level: headings, bullet lists, numbered lists, rules, paragraphs
        function renderMarkdown(container, text) {
            const lines = text.split(NL);
            let i = 0;
            let para = [];

            function flushPara() {
                if (!para.length) { return; }
                const p = document.createElement('div');
                p.className = 'md-p';
                parseInline(p, para.join(' '));
                container.appendChild(p);
                para = [];
            }

            while (i < lines.length) {
                const raw = lines[i];
                const line = raw.trim();

                if (!line) { flushPara(); i++; continue; }

                if (line === '---' || line === '***' || line === '___') {
                    flushPara();
                    const hr = document.createElement('div');
                    hr.className = 'md-hr';
                    container.appendChild(hr);
                    i++;
                    continue;
                }

                if (line.charAt(0) === '#') {
                    let level = 0;
                    while (level < line.length && line.charAt(level) === '#') { level++; }
                    if (level <= 6 && line.charAt(level) === ' ') {
                        flushPara();
                        const hd = document.createElement('div');
                        hd.className = 'md-h md-h' + Math.min(level, 3);
                        parseInline(hd, line.slice(level + 1).trim());
                        container.appendChild(hd);
                        i++;
                        continue;
                    }
                }

                if (isBullet(line)) {
                    flushPara();
                    const ul = document.createElement('ul');
                    ul.className = 'md-list';
                    while (i < lines.length && isBullet(lines[i].trim())) {
                        const li = document.createElement('li');
                        parseInline(li, stripBullet(lines[i].trim()));
                        ul.appendChild(li);
                        i++;
                    }
                    container.appendChild(ul);
                    continue;
                }

                if (numberedLen(line) > 0) {
                    flushPara();
                    const ol = document.createElement('ol');
                    ol.className = 'md-list';
                    while (i < lines.length && numberedLen(lines[i].trim()) > 0) {
                        const t = lines[i].trim();
                        const li = document.createElement('li');
                        parseInline(li, t.slice(numberedLen(t)).trim());
                        ol.appendChild(li);
                        i++;
                    }
                    container.appendChild(ol);
                    continue;
                }

                para.push(line);
                i++;
            }
            flushPara();
        }

        // Splits on fenced code blocks, then renders each prose part as
        // markdown (agent messages) or plain text (your own messages).
        function renderContent(container, text, useMarkdown) {
            const parts = text.split(FENCE);
            parts.forEach((part, i) => {
                if (i % 2 === 1) {
                    const nl = part.indexOf(NL);
                    const lang = nl === -1 ? '' : part.slice(0, nl).trim();
                    let code = nl === -1 ? part : part.slice(nl + 1);
                    if (code.charAt(code.length - 1) === NL) { code = code.slice(0, -1); }
                    const pre = document.createElement('pre');
                    pre.className = 'code-block';
                    if (lang) {
                        const label = document.createElement('div');
                        label.className = 'code-lang';
                        label.textContent = lang;
                        pre.appendChild(label);
                    }
                    const codeEl = document.createElement('code');
                    codeEl.textContent = code;
                    pre.appendChild(codeEl);
                    pre.appendChild(makeCopyButton(code));
                    container.appendChild(pre);
                } else if (part.trim()) {
                    if (useMarkdown) {
                        renderMarkdown(container, part);
                    } else {
                        const p = document.createElement('div');
                        p.className = 'chat-text';
                        p.textContent = part.trim();
                        container.appendChild(p);
                    }
                }
            });
        }

        // Pure DOM rendering - no state tracking. Used both for live messages
        // and when replaying chatLog on restore.
        function renderMessage(text, sender) {
            const wrapper = document.createElement('div');
            wrapper.className = 'message-wrapper ' + sender.toLowerCase();
            const bubble = document.createElement('div');
            bubble.className = 'chat-bubble ' + sender.toLowerCase();
            renderContent(bubble, text, sender === 'Agent');
            wrapper.appendChild(bubble);
            chatWindow.appendChild(wrapper);
            chatWindow.scrollTop = chatWindow.scrollHeight;
        }

        function addMessage(text, sender = 'Agent') {
            chatLog.push({ text, sender });
            saveState();
            renderMessage(text, sender);
        }

        // ADDED: tool-call trace.
        // UPDATE messages collapse into one growing group per turn, so a long
        // agentic run shows "13 steps" instead of thirteen separate bubbles.
        let currentTrace = null;

        function ensureTrace() {
            if (currentTrace) { return currentTrace; }
            const details = document.createElement('details');
            details.className = 'tool-trace';
            details.open = true;

            const summary = document.createElement('summary');
            summary.innerHTML = CHEVRON_ICON;
            const label = document.createElement('span');
            label.textContent = 'Working';
            summary.appendChild(label);
            details.appendChild(summary);

            const list = document.createElement('div');
            list.className = 'tool-trace-steps';
            details.appendChild(list);

            chatWindow.appendChild(details);
            chatWindow.scrollTop = chatWindow.scrollHeight;
            currentTrace = { el: details, label: label, list: list, count: 0 };
            return currentTrace;
        }

        function addTraceStep(text) {
            const t = ensureTrace();
            t.count++;
            const step = document.createElement('div');
            step.className = 'tool-trace-step';
            step.textContent = text;
            t.list.appendChild(step);
            t.label.textContent = t.count === 1 ? '1 step' : t.count + ' steps';
            chatWindow.scrollTop = chatWindow.scrollHeight;
        }

        function finalizeTrace() {
            if (currentTrace) {
                currentTrace.el.open = false;
                currentTrace = null;
            }
        }

        function addApprovalCard(p) {
            const wrapper = document.createElement('div');
            wrapper.className = 'message-wrapper agent';
            wrapper.id = 'approval-' + p.id;

            const card = document.createElement('div');
            card.className = 'approval-card';

            const header = document.createElement('div');
            header.className = 'approval-header';
            header.textContent = 'Write to ' + p.path + '?';
            card.appendChild(header);

            const pre = document.createElement('pre');
            pre.className = 'code-block';
            const codeEl = document.createElement('code');
            codeEl.textContent = p.content;
            pre.appendChild(codeEl);
            pre.appendChild(makeCopyButton(p.content));
            card.appendChild(pre);

            const buttons = document.createElement('div');
            buttons.className = 'approval-buttons';

            const approve = document.createElement('button');
            approve.className = 'btn-approve';
            approve.type = 'button';
            approve.textContent = 'Approve';
            approve.addEventListener('click', () => resolveApproval(p.id, true));

            const reject = document.createElement('button');
            reject.className = 'btn-reject';
            reject.type = 'button';
            reject.textContent = 'Reject';
            reject.addEventListener('click', () => resolveApproval(p.id, false));

            buttons.appendChild(approve);
            buttons.appendChild(reject);
            card.appendChild(buttons);
            wrapper.appendChild(card);
            chatWindow.appendChild(wrapper);
            chatWindow.scrollTop = chatWindow.scrollHeight;
        }

        function resolveApproval(id, approved) {
            vscode.postMessage({ type: 'approval', id: id, approved: approved });
            const el = document.getElementById('approval-' + id);
            const btns = el && el.querySelector('.approval-buttons');
            if (btns) {
                btns.textContent = approved ? '✓ Approved' : '✗ Rejected';
            }
            if (!approved && el) {
                const note = document.createElement('div');
                note.className = 'code-lang';
                note.textContent = 'Not written — copy from above if you want it';
                el.querySelector('.approval-card').appendChild(note);
            }
            showTypingIndicator();
        }

        cancelButton.addEventListener('click', () => {
            vscode.postMessage({ type: 'cancel' });
            cancelButton.style.display = 'none';
        });

        function resizeTextarea() {
            textarea.style.height = 'auto';
            textarea.style.height = textarea.scrollHeight + 'px';
        }

        textarea.addEventListener('input', resizeTextarea);
        resizeTextarea();

        window.addEventListener('message',(event)=>{
        const message = event.data;
        if(message.type==='connectionState'){
            setConnectionState(message.state);
            return;
        }
        if(message.type === 'quota'){
            quotaText.textContent = message.text;
            return;
            }
        if(message.type==='ask'){
            removeTypingIndicator();
            addApprovalCard(message.payload);
            return;
        }
        // ADDED: updates feed the trace, and the loading dots stay up
        // afterwards so the panel never looks idle mid-task.
        if(message.type==='update'){
            removeTypingIndicator();
            addTraceStep(message.text);
            showTypingIndicator();
            return;
        }
        removeTypingIndicator();
        if(message.type==='done'){
            finalizeTrace();
            addMessage(message.text,'Agent');
            }
            else if(message.type==='status'){
                addMessage(message.text,'System');
                }
        if(message.type==='done' || (message.type ==='status' && message.text.includes('error'))){
        textarea.disabled=false;
        sendButton.disabled=false;
        textarea.placeholder="Type your prompt here...";
        textarea.focus();
        cancelButton.style.display = 'none';
        }

        });

        function showTypingIndicator() {
            if (document.getElementById('typing-indicator')) return;

            const wrapper = document.createElement('div');
            wrapper.id = 'typing-indicator';
            wrapper.className = 'message-wrapper agent';

            const bubble = document.createElement('div');
            bubble.className = 'chat-bubble agent typing-indicator';
            bubble.innerHTML = '<span class="dot"></span><span class="dot"></span><span class="dot"></span>';

            wrapper.appendChild(bubble);
            chatWindow.appendChild(wrapper);
            chatWindow.scrollTop = chatWindow.scrollHeight;
        }

        function removeTypingIndicator() {
            const indicator = document.getElementById('typing-indicator');
            if (indicator) {
                indicator.remove();
            }
        }

        const MAX_PROMPT_LENGTH=4000;

        function submitPrompt() {
            const prompt = textarea.value.trim();
            if (!prompt || textarea.disabled) {
                return;
            }
            if (prompt.length > MAX_PROMPT_LENGTH) {
                addMessage('Max length is ' + MAX_PROMPT_LENGTH + ' chars - please shorten it.', 'System');
                return;
            }

            currentTrace = null;
            addMessage(prompt, 'You');
            vscode.postMessage({type:'prompt',text:prompt});
            textarea.value = '';
            resizeTextarea();

            //lock user from inputtinh while aent workds
            textarea.disabled=true;
            sendButton.disabled=true;

            showTypingIndicator();
            cancelButton.style.display = 'inline-flex';
        }

        sendButton.addEventListener('click', submitPrompt);

        // ADDED: Enter sends, Shift+Enter inserts a newline.
        textarea.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                submitPrompt();
            }
        });
    </script>
</body>
</html>`;
}
//secruity feature, new nonce generated each time
//nonce is a temp password such that certain script code only runs if it has this nonce with it
// if a hacker tries to inject malicious code, it will be rejected since they dont have the nonce
function getNonce(): string {
    let text = '';
    const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    for (let i = 0; i < 32; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
}
